ex1:
	ncverilog +access+r mips32test.v mips32.v
ex2:
	ncverilog +access+r sum32test.v mips32.v
ex3:
	ncverilog +access+r fib32test.v mips32.v
clean:
	rm -rf INCA_libs ncverilog.log ncverilog.key dump.vcd sim.log
	rm -rf *.vcd *.trn *.dsn
