ex1:
	ncverilog +access+r test.v mips32.v addrdec.v busarb.v dmac.v done_mux.v sram.v sram_start.v timer.v define.h
clean:
	rm -rf INCA_libs ncverilog.log ncverilog.key dump.vcd sim.log
	rm -rf *.vcd *.trn *.dsn
