ex1:
	ncverilog +access+r mipstest.v mips.v
ex3:
	ncverilog +access+r fibtest.v mips.addi.v
ex4:
	ncverilog +access+r sumtest.v mips.addi.v
clean:
	rm -rf INCA_libs ncverilog.log ncverilog.key dump.vcd sim.log
